package homeworks.enums;

public enum Homework {
    // 1. Week
    WEEK1_HELLO_WORLD,
    WEEK1_VARIABLES,
    WEEK1_DATA_TYPES,
    WEEK1_CONDITIONALS,
    WEEK1_RECAP_DEMO_1,
    WEEK1_SWITCH,
    WEEK1_LOOPS,
    WEEK1_ARRAYS,
    WEEK1_RECAP_DEMO_2,
    WEEK1_MULTI_DIMENSIONAL_ARRAY,
    WEEK1_STRINGS,
    WEEK1_MINI_PROJE_ASAL_SAYILAR,
    WEEK1_MINI_PROJE_SESLI_HARFLER,
    WEEK1_MINI_PROJE_MUKEMMEL_SAYILAR,
    WEEK1_MINI_PROJE_ARKADAS_SAYILAR,
    WEEK1_MINI_PROJE_SAYI_BULMA,

    // 2. Week
    WEEK2_METHODS,
}
