package homeworks.enums;

public enum Homework {
    // 1st Week
    WEEK1_HELLO_WORLD,
    WEEK1_VARIABLES,
    WEEK1_DATA_TYPES,
    WEEK1_CONDITIONALS,
    WEEK1_RECAP_DEMO_1,
    WEEK1_SWITCH,
    WEEK1_LOOPS,
    WEEK1_ARRAYS,
    WEEK1_RECAP_DEMO_2,
    WEEK1_MULTI_DIMENSIONAL_ARRAY,
    WEEK1_STRINGS,
    WEEK1_MINI_PROJE_ASAL_SAYILAR,
    WEEK1_MINI_PROJE_SESLI_HARFLER,
    WEEK1_MINI_PROJE_MUKEMMEL_SAYILAR,
    WEEK1_MINI_PROJE_ARKADAS_SAYILAR,
    WEEK1_MINI_PROJE_SAYI_BULMA,

    // 2nd Week
    WEEK2_METHODS,
    WEEK2_METHODS2,
    WEEK2_CLASSES,
    WEEK2_RECAP_DEMO_CLASSES,
    WEEK2_CLASSES_WITH_ATTRIBUTES,
    WEEK2_METHOD_OVERLOADING,
    WEEK2_INHERITANCE,
    WEEK2_INHERITANCE_DEMO,

    // 3rd Week
    WEEK3_POLYMORPHISM_DEMO,
    WEEK3_OVERRIDING,
    WEEK3_ABSTRACT_CLASSES,
    WEEK3_ABSTRACT_DEMO,
    WEEK3_INTERFACES,
    WEEK3_INTERFACE_DEMO,
}
